name: deploy

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    # env:
    #   working-directory: ./apps/server

    strategy:
      matrix:
        node-version: [18.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: |
          npm install -g pnpm@6.32.9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'
